- name: Create tomcat environment
  hosts: "BACK"
  sudo: True
  vars:
    #jre vars
    download_folder: /opt
    download_url: http://download.oracle.com/otn-pub/java/jdk/8u60-b27/jre-8u60-linux-x64.tar.gz
    java_name: "{{download_folder}}/jre1.8.0_60"
    java_archive: "{{download_folder}}/jre-8u60-linux-x64.tar.gz"

    #tomcat vars
    catalina_home: /appli/tomcat
    tomcat_major: 8
    tomcat_version: 8.0.32
    tomcat_tgz_url: https://www.apache.org/dist/tomcat/tomcat-{{tomcat_major}}/v8/bin/apache-tomcat-{{ tomcat_version }}.tar.gz
    tomcat_setenv: /appli/tomcat/bin
    tomcat_service: /etc/init.d/

  tasks:

    - name: install tools
      yum:  name={{ item }} state=latest
      with_items:
       - wget
       - tar
       - python-setuptools
       - libselinux-python
       - curl
       - syslog

    - name: download Java
      command: "wget -q -O {{java_archive}} --no-check-certificate --no-cookies --header 'Cookie: oraclelicense=accept-securebackup-cookie' {{download_url}} creates={{java_archive}}"

    - name: unpack archive
      command: "tar -zxf {{java_archive}} -C {{download_folder}} creates={{java_name}}"

    - name: fix ownership
      file: state=directory path={{java_name}} recurse=yes

    - name: make Java available for system
      command: 'alternatives --install "/usr/bin/java" "java" "{{java_name}}/bin/java" 2000'

    - name: clean up
      file: state=absent path={{java_archive}}

    - name: create tomcat home directory
      file: path={{ catalina_home }} state=directory mode=0755

    - name: add tomcat group
      group: name=tomcat state=present

    - name: add user tomcat
      user: name=tomcat home={{ catalina_home }} shell=/sbin/nologin state=present

    - name: make tomcat owner on catalina home directory
      file: path={{ catalina_home }} owner=tomcat recurse=yes

    - name: download tomcat archive
      get_url: url={{ tomcat_tgz_url }} dest=/home/vagrant

    - name: unarchive tomcat archive
      unarchive: src=/home/vagrant/apache-tomcat-{{ tomcat_version }}.tar.gz dest={{ catalina_home }}

    - name: remove tomcat directoryies
      file: path={{ item }} state=absent
      with_items:
       - \"{{ catalina_home }}\"/webapps/docs
       - \"{{ catalina_home }}\"/webapps/examples
       - \"{{ catalina_home }}\"/webapps/host-manager
       - \"{{ catalina_home }}\"/webapps/manager
       - \"{{ catalina_home }}\"/webapps/ROOT

    - name: remove tomcat archive
      yum: name=apache-tomcat-{{ tomcat_version }}.tar.gz state=absent

    - name: tomcat as a service
      file: src=templates/tomcat/tomcat dst={{tomcat_service}} mode=0755

    - name: configure setenv.sh configuration file
      file: src=templates/tomcat/setenv.sh dest={{tomcat_setenv}}

    - name: update run-levels for tomcat service
      command: update-rc.d tomcat defaults

    - name: start tomcat service
      service: name=tomcat state=restarted
